# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Bomber.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateTimeEdit, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(611, 316)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 121, 20))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.datetime_start = QDateTimeEdit(self.centralwidget)
        self.datetime_start.setObjectName(u"datetime_start")
        self.datetime_start.setGeometry(QRect(70, 60, 194, 22))
        self.version_major = QSpinBox(self.centralwidget)
        self.version_major.setObjectName(u"version_major")
        self.version_major.setGeometry(QRect(80, 100, 42, 22))
        self.version_major.setMaximum(9)
        self.version_major.setValue(3)
        self.version_minor = QSpinBox(self.centralwidget)
        self.version_minor.setObjectName(u"version_minor")
        self.version_minor.setGeometry(QRect(130, 100, 42, 22))
        self.version_minor.setMaximum(9)
        self.version_minor.setSingleStep(0)
        self.version_minor.setValue(2)
        self.version_minor2 = QSpinBox(self.centralwidget)
        self.version_minor2.setObjectName(u"version_minor2")
        self.version_minor2.setGeometry(QRect(180, 100, 42, 22))
        self.datetime_end = QDateTimeEdit(self.centralwidget)
        self.datetime_end.setObjectName(u"datetime_end")
        self.datetime_end.setGeometry(QRect(350, 60, 194, 22))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 54, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 60, 54, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(290, 60, 54, 16))
        self.max_theads = QSlider(self.centralwidget)
        self.max_theads.setObjectName(u"max_theads")
        self.max_theads.setGeometry(QRect(350, 100, 160, 18))
        self.max_theads.setMinimum(64)
        self.max_theads.setMaximum(4096)
        self.max_theads.setSingleStep(16)
        self.max_theads.setValue(512)
        self.max_theads.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 100, 91, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 101, 16))
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(10, 160, 301, 111))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(320, 220, 191, 23))
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setValue(0)
        self.max_thread_display = QLabel(self.centralwidget)
        self.max_thread_display.setObjectName(u"max_thread_display")
        self.max_thread_display.setGeometry(QRect(530, 100, 54, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(320, 170, 61, 16))
        self.total_task = QLabel(self.centralwidget)
        self.total_task.setObjectName(u"total_task")
        self.total_task.setGeometry(QRect(500, 170, 71, 16))
        self.total_task.setAlignment(Qt.AlignCenter)
        self.finished_task = QLabel(self.centralwidget)
        self.finished_task.setObjectName(u"finished_task")
        self.finished_task.setGeometry(QRect(380, 170, 71, 16))
        self.finished_task.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(470, 170, 54, 16))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(470, 150, 54, 16))
        self.current_threads = QLabel(self.centralwidget)
        self.current_threads.setObjectName(u"current_threads")
        self.current_threads.setGeometry(QRect(380, 150, 71, 16))
        self.current_threads.setAlignment(Qt.AlignCenter)
        self.maxinum_tasks = QLabel(self.centralwidget)
        self.maxinum_tasks.setObjectName(u"maxinum_tasks")
        self.maxinum_tasks.setGeometry(QRect(500, 150, 71, 16))
        self.maxinum_tasks.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(320, 150, 61, 16))
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(320, 250, 75, 24))
        self.stop = QPushButton(self.centralwidget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(410, 250, 75, 24))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(470, 190, 54, 16))
        self.finished_task_2 = QLabel(self.centralwidget)
        self.finished_task_2.setObjectName(u"finished_task_2")
        self.finished_task_2.setGeometry(QRect(380, 190, 71, 16))
        self.finished_task_2.setAlignment(Qt.AlignCenter)
        self.total_task_2 = QLabel(self.centralwidget)
        self.total_task_2.setObjectName(u"total_task_2")
        self.total_task_2.setGeometry(QRect(500, 190, 71, 16))
        self.total_task_2.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(320, 190, 61, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 611, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u8f70\u70b8\u673a", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ota\u5305\u8f70\u70b8\u673a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u53f7", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u8d77\u59cb\u65f6\u95f4", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u6b62\u65f6\u95f4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u5e76\u884c\u7ebf\u7a0b\u6570", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6\u5230\u7684\u7ed3\u679c:", None))
        self.max_thread_display.setText(QCoreApplication.translate("MainWindow", u"512", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5b8c\u6210\u6570\u91cf\uff1a", None))
        self.total_task.setText(QCoreApplication.translate("MainWindow", u"86400", None))
        self.finished_task.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.current_threads.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.maxinum_tasks.setText(QCoreApplication.translate("MainWindow", u"512", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u7ebf\u7a0b", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u8f70\u70b8", None))
        self.stop.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62\u8f70\u70b8", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.finished_task_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.total_task_2.setText(QCoreApplication.translate("MainWindow", u"86400", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001\u6570\u91cf\uff1a", None))
    # retranslateUi

