# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'WTF.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QCheckBox, QComboBox,
    QDateTimeEdit, QDial, QDoubleSpinBox, QFontComboBox,
    QKeySequenceEdit, QLCDNumber, QLineEdit, QPlainTextEdit,
    QProgressBar, QPushButton, QRadioButton, QScrollBar,
    QSizePolicy, QSlider, QSpinBox, QStackedWidget,
    QTextEdit, QTimeEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(945, 517)
        self.pushButton_4 = QPushButton(Form)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(170, 120, 171, 24))
        self.pushButton_5 = QPushButton(Form)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(530, 450, 171, 24))
        self.pushButton_6 = QPushButton(Form)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(190, 140, 171, 24))
        self.pushButton_7 = QPushButton(Form)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(200, 150, 171, 24))
        self.pushButton_8 = QPushButton(Form)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(210, 160, 171, 24))
        self.pushButton_9 = QPushButton(Form)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(220, 170, 171, 24))
        self.pushButton_10 = QPushButton(Form)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(230, 180, 171, 24))
        self.pushButton_11 = QPushButton(Form)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(240, 190, 171, 24))
        self.pushButton_12 = QPushButton(Form)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(250, 200, 171, 24))
        self.pushButton_13 = QPushButton(Form)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(260, 210, 171, 24))
        self.pushButton_14 = QPushButton(Form)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(270, 220, 171, 24))
        self.pushButton_15 = QPushButton(Form)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(280, 230, 171, 24))
        self.pushButton_16 = QPushButton(Form)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(290, 240, 171, 24))
        self.pushButton_17 = QPushButton(Form)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(300, 250, 171, 24))
        self.pushButton_18 = QPushButton(Form)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(310, 260, 171, 24))
        self.pushButton_19 = QPushButton(Form)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(320, 270, 171, 24))
        self.pushButton_20 = QPushButton(Form)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(330, 280, 171, 24))
        self.pushButton_21 = QPushButton(Form)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(340, 290, 171, 24))
        self.pushButton_22 = QPushButton(Form)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(350, 300, 171, 24))
        self.pushButton_23 = QPushButton(Form)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(360, 310, 171, 24))
        self.pushButton_24 = QPushButton(Form)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(370, 320, 171, 24))
        self.pushButton_25 = QPushButton(Form)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(380, 330, 171, 24))
        self.pushButton_26 = QPushButton(Form)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(390, 340, 171, 24))
        self.pushButton_27 = QPushButton(Form)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(400, 350, 171, 24))
        self.pushButton_28 = QPushButton(Form)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(410, 360, 171, 24))
        self.pushButton_29 = QPushButton(Form)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(420, 370, 171, 24))
        self.pushButton_30 = QPushButton(Form)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(430, 380, 171, 24))
        self.pushButton_31 = QPushButton(Form)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(440, 390, 171, 24))
        self.pushButton_32 = QPushButton(Form)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(450, 400, 171, 24))
        self.pushButton_33 = QPushButton(Form)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(460, 410, 171, 24))
        self.pushButton_34 = QPushButton(Form)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(470, 420, 171, 24))
        self.calendarWidget = QCalendarWidget(Form)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(90, 280, 248, 183))
        self.calendarWidget.setSelectedDate(QDate(2077, 1, 3))
        self.lcdNumber = QLCDNumber(Form)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(680, 220, 64, 23))
        self.calendarWidget_2 = QCalendarWidget(Form)
        self.calendarWidget_2.setObjectName(u"calendarWidget_2")
        self.calendarWidget_2.setGeometry(QRect(710, 290, 248, 183))
        self.calendarWidget_3 = QCalendarWidget(Form)
        self.calendarWidget_3.setObjectName(u"calendarWidget_3")
        self.calendarWidget_3.setGeometry(QRect(380, 80, 248, 183))
        self.doubleSpinBox = QDoubleSpinBox(Form)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(160, 110, 62, 22))
        self.doubleSpinBox_2 = QDoubleSpinBox(Form)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(390, 440, 62, 22))
        self.doubleSpinBox_3 = QDoubleSpinBox(Form)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(30, 240, 62, 22))
        self.doubleSpinBox_4 = QDoubleSpinBox(Form)
        self.doubleSpinBox_4.setObjectName(u"doubleSpinBox_4")
        self.doubleSpinBox_4.setGeometry(QRect(160, 240, 62, 22))
        self.doubleSpinBox_5 = QDoubleSpinBox(Form)
        self.doubleSpinBox_5.setObjectName(u"doubleSpinBox_5")
        self.doubleSpinBox_5.setGeometry(QRect(790, 150, 62, 22))
        self.doubleSpinBox_6 = QDoubleSpinBox(Form)
        self.doubleSpinBox_6.setObjectName(u"doubleSpinBox_6")
        self.doubleSpinBox_6.setGeometry(QRect(680, 220, 62, 22))
        self.doubleSpinBox_7 = QDoubleSpinBox(Form)
        self.doubleSpinBox_7.setObjectName(u"doubleSpinBox_7")
        self.doubleSpinBox_7.setGeometry(QRect(200, 40, 62, 22))
        self.doubleSpinBox_8 = QDoubleSpinBox(Form)
        self.doubleSpinBox_8.setObjectName(u"doubleSpinBox_8")
        self.doubleSpinBox_8.setGeometry(QRect(810, 460, 62, 22))
        self.doubleSpinBox_9 = QDoubleSpinBox(Form)
        self.doubleSpinBox_9.setObjectName(u"doubleSpinBox_9")
        self.doubleSpinBox_9.setGeometry(QRect(560, 500, 62, 22))
        self.doubleSpinBox_10 = QDoubleSpinBox(Form)
        self.doubleSpinBox_10.setObjectName(u"doubleSpinBox_10")
        self.doubleSpinBox_10.setGeometry(QRect(560, 500, 62, 22))
        self.doubleSpinBox_11 = QDoubleSpinBox(Form)
        self.doubleSpinBox_11.setObjectName(u"doubleSpinBox_11")
        self.doubleSpinBox_11.setGeometry(QRect(670, 150, 62, 22))
        self.doubleSpinBox_12 = QDoubleSpinBox(Form)
        self.doubleSpinBox_12.setObjectName(u"doubleSpinBox_12")
        self.doubleSpinBox_12.setGeometry(QRect(60, 160, 62, 22))
        self.dial = QDial(Form)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(300, 50, 50, 64))
        self.dial_2 = QDial(Form)
        self.dial_2.setObjectName(u"dial_2")
        self.dial_2.setGeometry(QRect(770, 150, 50, 64))
        self.dial_3 = QDial(Form)
        self.dial_3.setObjectName(u"dial_3")
        self.dial_3.setGeometry(QRect(30, 20, 50, 64))
        self.dial_4 = QDial(Form)
        self.dial_4.setObjectName(u"dial_4")
        self.dial_4.setGeometry(QRect(20, 370, 50, 64))
        self.plainTextEdit = QPlainTextEdit(Form)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(100, 60, 104, 71))
        self.plainTextEdit_2 = QPlainTextEdit(Form)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(740, 50, 104, 71))
        self.plainTextEdit_3 = QPlainTextEdit(Form)
        self.plainTextEdit_3.setObjectName(u"plainTextEdit_3")
        self.plainTextEdit_3.setGeometry(QRect(770, 220, 104, 71))
        self.plainTextEdit_4 = QPlainTextEdit(Form)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(520, 290, 104, 71))
        self.plainTextEdit_5 = QPlainTextEdit(Form)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(620, 120, 104, 71))
        self.horizontalScrollBar = QScrollBar(Form)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setGeometry(QRect(380, 30, 160, 16))
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.verticalSlider = QSlider(Form)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(670, 270, 18, 160))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.keySequenceEdit = QKeySequenceEdit(Form)
        self.keySequenceEdit.setObjectName(u"keySequenceEdit")
        self.keySequenceEdit.setGeometry(QRect(450, 480, 113, 20))
        self.spinBox = QSpinBox(Form)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(650, 50, 42, 22))
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(210, 480, 113, 20))
        self.textEdit = QTextEdit(Form)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(130, 160, 104, 71))
        self.fontComboBox = QFontComboBox(Form)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setGeometry(QRect(500, 20, 223, 22))
        self.lineEdit_2 = QLineEdit(Form)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(820, 190, 113, 20))
        self.checkBox = QCheckBox(Form)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(300, 40, 79, 20))
        self.checkBox_2 = QCheckBox(Form)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(310, 50, 79, 20))
        self.checkBox_3 = QCheckBox(Form)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(320, 60, 79, 20))
        self.checkBox_4 = QCheckBox(Form)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(510, 250, 79, 20))
        self.checkBox_5 = QCheckBox(Form)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(520, 260, 79, 20))
        self.checkBox_6 = QCheckBox(Form)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(530, 270, 79, 20))
        self.checkBox_7 = QCheckBox(Form)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(550, 290, 79, 20))
        self.checkBox_8 = QCheckBox(Form)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(560, 300, 79, 20))
        self.checkBox_9 = QCheckBox(Form)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(570, 310, 79, 20))
        self.checkBox_10 = QCheckBox(Form)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(580, 320, 79, 20))
        self.checkBox_11 = QCheckBox(Form)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(590, 330, 79, 20))
        self.radioButton = QRadioButton(Form)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(340, 400, 95, 20))
        self.radioButton_2 = QRadioButton(Form)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(780, 130, 95, 20))
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(640, 220, 120, 80))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.stackedWidget_2 = QStackedWidget(self.page)
        self.stackedWidget_2.setObjectName(u"stackedWidget_2")
        self.stackedWidget_2.setGeometry(QRect(30, 20, 111, 81))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.timeEdit = QTimeEdit(self.page)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(0, 60, 118, 22))
        self.progressBar_2 = QProgressBar(self.page)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(10, 20, 118, 23))
        self.progressBar_2.setValue(24)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.comboBox = QComboBox(Form)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(660, 90, 68, 22))
        self.dateTimeEdit = QDateTimeEdit(Form)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(540, 370, 194, 22))
        self.dateTimeEdit_2 = QDateTimeEdit(Form)
        self.dateTimeEdit_2.setObjectName(u"dateTimeEdit_2")
        self.dateTimeEdit_2.setGeometry(QRect(100, 0, 194, 22))
        self.keySequenceEdit_2 = QKeySequenceEdit(Form)
        self.keySequenceEdit_2.setObjectName(u"keySequenceEdit_2")
        self.keySequenceEdit_2.setGeometry(QRect(320, 460, 113, 20))
        self.progressBar = QProgressBar(Form)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(250, 250, 118, 23))
        self.progressBar.setValue(24)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u8fd9\u5565\u6211\u4e5f\u4e0d\u77e5\u9053", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_10.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_11.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_12.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_13.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_14.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_15.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_16.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_17.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_18.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_19.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_20.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_21.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_22.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_23.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_24.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_25.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_26.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_27.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_28.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_29.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_30.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_31.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_32.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_33.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.pushButton_34.setText(QCoreApplication.translate("Form", u"Pygame\u6211\u5e26\u4f60\u4eec\u6253", None))
        self.checkBox.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_2.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_3.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_4.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_5.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_6.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_7.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_8.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_9.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_10.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.checkBox_11.setText(QCoreApplication.translate("Form", u"CheckBox", None))
        self.radioButton.setText(QCoreApplication.translate("Form", u"RadioButton", None))
        self.radioButton_2.setText(QCoreApplication.translate("Form", u"RadioButton", None))
    # retranslateUi

