# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'StudentWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(371, 273)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 60, 71, 21))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setOpenExternalLinks(False)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 140, 71, 21))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setOpenExternalLinks(False)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 120, 71, 21))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setOpenExternalLinks(False)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 40, 71, 21))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(False)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(70, 80, 71, 21))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setOpenExternalLinks(False)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(70, 100, 71, 21))
        self.label_10.setFrameShape(QFrame.NoFrame)
        self.label_10.setFrameShadow(QFrame.Plain)
        self.label_10.setTextFormat(Qt.PlainText)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setOpenExternalLinks(False)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(200, 60, 121, 21))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setOpenExternalLinks(False)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 140, 121, 21))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setOpenExternalLinks(False)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(200, 120, 121, 21))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setOpenExternalLinks(False)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(200, 40, 121, 21))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setOpenExternalLinks(False)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(200, 80, 121, 21))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setOpenExternalLinks(False)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 100, 121, 21))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setOpenExternalLinks(False)
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(40, 200, 81, 51))
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(150, 200, 81, 51))
        self.pushButton_3 = QPushButton(Form)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(260, 200, 81, 51))
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(110, 10, 121, 21))
        font = QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_14.setOpenExternalLinks(False)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(70, 160, 71, 21))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_15.setOpenExternalLinks(False)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(200, 160, 121, 21))
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setOpenExternalLinks(False)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u5b66\u751f\u4fe1\u606f", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u5b66\u53f7", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u5386\u53f2\u603b\u5206", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u6700\u9ad8/\u4f4e\u5206", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u540d\u79f0", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u5f53\u524d\u5206\u6570", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u6240\u5c5e\u73ed\u7ea7", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"1145", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"231313", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"11.4514/-191.9", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u6211\u4e0d\u5230\u554a", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"1919", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"1145\u73ed", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u5386\u53f2\u8bb0\u5f55", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u6210\u5c31\u8bb0\u5f55", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u53d1\u9001\u70b9\u8bc4", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\u5b66\u751f\u4fe1\u606f", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"\u5f53\u524d\u73ed\u6392", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"1145", None))
    # retranslateUi

